// try catch

try {
    var i = 1/a;
    console.log(i);
  }
  catch (exception_var) {
    console.log("OUCH! that hurt!");
    console.log(exception_var);
  }
  finally {
    console.log("it took a while but you are finally here!");
  }
